### ISSUE TITLE
Seitenformatierung

### ISSUE THREAD

**Issue by OliKue** [Sentiments-of-Bundestag/Dokumentation#4]
Ich glaube die Seiten sind als Buchseiten eingestellt was zu einer komischen Formatierung führt. 
Ist das so gewollt?

**Comment by borisfoko** [comment]
Es handelt sich um eine Zweiseite Formatierung wie es üblicherweise bei Bücher (Thesis, Wissenschaftliche Doku, etc.) der Fall ist.
